### ISSUE TITLE
Support for args and kwargs

### ISSUE THREAD

**Issue by saeedesmaili** [adriangalilea/streamlit-shortcuts#12]
It would be great if the button created by `streamlit_shortcuts.button` supported the args and kwargs from the [original `st.button`](https://docs.streamlit.io/develop/api-reference/widgets/st.button). For example, if I have multiple buttons which mainly do same things with slight differences, I'd like to have one single callback function and pass some kwargs to the function, instead of defining one function for each button.

**Comment by adriangalilea** [comment]
Good point, that should be easy to do.

Hopefully someone else can take a stab at it as I have 0 time.

But seems like literally passing down the args and kwargs would be sufficient.

**Comment by adriangalilea** [comment]
Closed in https://github.com/adriangalilea/streamlit-shortcuts/releases/tag/v0.1.5 😉
